# Generated by Django 4.1.4 on 2022-12-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
